-- MySQL Script generated by MySQL Workbench
-- 2024. ápr. 19., péntek, 10:33:21 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema merlin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'member' COMMENT 'active | closed | paused | Proposal',
  `parent_id` BIGINT NOT NULL COMMENT 'Tree structure',
  `config` TEXT NOT NULL COMMENT 'JSON string',
  `ranks` VARCHAR(255) NOT NULL DEFAULT 'members,admin' COMMENT 'comma-separated list',
  PRIMARY KEY (`id`),
  INDEX `parent_fk_idx` (`parent_id` ASC) VISIBLE,
  INDEX `name_idx` (`name` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `parent_fk`
    FOREIGN KEY (`parent_id`)
    REFERENCES `groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_hungarian_ci
COMMENT = 'groups ';


-- -----------------------------------------------------
-- Table `groups_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups_like` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `type` VARCHAR(32) NOT NULL DEFAULT 'like' COMMENT 'like|dislike',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'groups_id',
  PRIMARY KEY (`id`),
  INDEX `fk_user_like_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_like_users21_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users11`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users21`
    FOREIGN KEY (`parent_id`)
    REFERENCES `groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groups_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups_log` (
  `id` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL,
  `time` DATETIME NOT NULL,
  `event` TEXT NOT NULL COMMENT 'eventType  infos',
  `users_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `time` (`time` ASC) VISIBLE,
  INDEX `fk_groups_log_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_log`
    FOREIGN KEY (`parent_id`)
    REFERENCES `groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groups_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups_vote` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `value` INT NOT NULL COMMENT '1|2|3|4|5',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'groups_id',
  PRIMARY KEY (`id`),
  INDEX `fk_group_vote_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users121`
    FOREIGN KEY (`parent_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users221`
    FOREIGN KEY (`parent_id`)
    REFERENCES `groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `iplocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iplocks` (
  `id` BIGINT NOT NULL,
  `ip` VARCHAR(64) NOT NULL,
  `error_count` INT NOT NULL DEFAULT 0,
  `lock_time` INT NULL DEFAULT 0 COMMENT '0 - not locked | lock time start',
  PRIMARY KEY (`id`),
  INDEX `ip_index` (`ip` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_hungarian_ci;


-- -----------------------------------------------------
-- Table `members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rank` VARCHAR(128) NOT NULL DEFAULT 'member' COMMENT 'example: mermber | admin .  -see  rankas of group.',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'active | aspirant | closed | disabled | paused | draft',
  `users_id` BIGINT NOT NULL,
  `groups_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_members_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_groups`
    FOREIGN KEY (`groups_id`)
    REFERENCES `groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_hungarian_ci
COMMENT = 'User group memberships. A user can hold multiple positions in the same group';


-- -----------------------------------------------------
-- Table `members_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members_like` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT COMMENT 'time of lock start',
  `created_at` DATETIME NOT NULL,
  `type` VARCHAR(32) NOT NULL DEFAULT 'like' COMMENT 'like|dislike',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'members_id',
  PRIMARY KEY (`id`),
  INDEX `fk_user_like_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_like_users20_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users10`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users20`
    FOREIGN KEY (`parent_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Bad login attempt counter (if username is wrong)\n';


-- -----------------------------------------------------
-- Table `members_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members_log` (
  `id` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'members_id',
  `time` DATETIME NOT NULL,
  `event` TEXT NOT NULL COMMENT 'eventType  infos',
  `users_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `time` (`time` ASC) VISIBLE,
  INDEX `fk_members_log_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_log`
    FOREIGN KEY (`parent_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `members_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members_vote` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `value` INT NOT NULL COMMENT '1|2|3|4|5',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'members_id',
  PRIMARY KEY (`id`),
  INDEX `fk_user_like_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_like_users2_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users120`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users220`
    FOREIGN KEY (`parent_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL COMMENT 'hash',
  `realname` VARCHAR(64) NOT NULL,
  `avatar` VARCHAR(128) NOT NULL COMMENT 'absolute url',
  `email_verifyed` TINYINT NOT NULL COMMENT '0 - no | 1 -yes',
  `status` VARCHAR(16) NOT NULL DEFAULT 'notActivated' COMMENT 'enabled | disabled | deleted | locked | notActivated',
  `two_factor` TINYINT NOT NULL DEFAULT 0 COMMENT '0 -no | 1 -yes',
  `two_factor_secret` VARCHAR(128) NOT NULL,
  `error_count` INT NOT NULL COMMENT 'Bad login attempt counter (username correct)',
  `lock_time` INT NULL DEFAULT 0 COMMENT 'time of lock start|0-notlocked',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_hungarian_ci
COMMENT = 'registered users';


-- -----------------------------------------------------
-- Table `users_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_like` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `type` VARCHAR(32) NOT NULL DEFAULT 'like' COMMENT 'like|dislike',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'users_id',
  PRIMARY KEY (`id`),
  INDEX `fk_user_like_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_like_users2_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_log` (
  `id` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL,
  `time` DATETIME NOT NULL,
  `event` TEXT NOT NULL COMMENT 'eventType  infos',
  `users_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `time` (`time` ASC) VISIBLE,
  INDEX `fk_users_log` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_log`
    FOREIGN KEY (`parent_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_vote` (
  `id` BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `value` INT NOT NULL COMMENT '1|2|3|4|5',
  `created_by` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL COMMENT 'users_id',
  PRIMARY KEY (`id`),
  INDEX `fk_user_like_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_user_like_users2_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_like_users12`
    FOREIGN KEY (`created_by`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_users22`
    FOREIGN KEY (`parent_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Data for table `groups`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `groups` (`id`, `name`, `description`, `status`, `parent_id`, `config`, `ranks`) VALUES (1, 'Root', 'Root', 'active', 0, '{}', 'members');
INSERT INTO `groups` (`id`, `name`, `description`, `status`, `parent_id`, `config`, `ranks`) VALUES (2, 'Registered', 'Registered users', 'active', 1, '{}', 'members');
INSERT INTO `groups` (`id`, `name`, `description`, `status`, `parent_id`, `config`, `ranks`) VALUES (3, 'Sysem_admins', 'System administrators', 'active', 1, '{}', 'members');

COMMIT;


-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `users` (`id`, `username`, `email`, `password`, `realname`, `avatar`, `email_verifyed`, `status`, `two_factor`, `two_factor_secret`, `error_count`, `lock_time`) VALUES (1, 'algorithm', 'none', 'none', 'algorithm', 'none', 0, 'active', 0, '', 0, 0);
INSERT INTO `users` (`id`, `username`, `email`, `password`, `realname`, `avatar`, `email_verifyed`, `status`, `two_factor`, `two_factor_secret`, `error_count`, `lock_time`) VALUES (2, 'guest', 'none1', 'none1', 'guest', 'none', 0, 'active', 0, ' ', 0, 0);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
