export var lngTokens = {
    "OK":"Rendben",
    "CANCEL":"Mégsem",
    "BACK":"Vissza",
    "SAVE":"Tárolás",
    "SAVED":"Tárolva",
    "SEND":"Küld",
    "EDIT":"Módosítás",
    "ADD":"Új hozzáadása",
    "DELETE":"Törlés",
    "DELETED":"Törölve",
    "SHOW":"Megnéz",
    "PRINT":"Nyomtatás",
    "YES":"Igen",
    "NO":"Nem",
    "ACCESDENIED":"Hozzáférés nem engedélyezett",
    "NODATA":"Nincs adat",
    "SEARCH":"Keresés",
    "CLEARFILTER":"Szűrés törlése",
	"SETUP":"Beállítás",
    "NAME":"Név",
	"SUREDELETE":"Biztos törölni akarod?",
    "NOT_FOUND":"Nincs ilyen",
    "FLOWKEY_ERROR":"Lejárt a munkamenet. Lehet, hogy túl hosszú várakozás.",

    "TOTAL":"Összesen",
    "LINES":"sor",
    "FIRST":"Első",
    "PREVIOUS":"Elöző",
    "NEXT":"Következő",
    "LAST":"Utolsó",
    "ORDER":"Rendezés",

    "HOME":"Kezdőlap",
    "LOGOUT":"Kijelentkezés",
    "NEWVERSION":"Új verzió érhető el",
    "LOGIN":"Bejelentkezés",
    "REGISTRATION":"Regisztráció",
    "DESCRIPTION":"Ismertető",
	"SWDOC":"Dokumentáció",
	"USERS":"Felhasználók",
	"GROUPS":"Csoportok",
    "PONZOR":"Adomány",
    "PRODUCTS":"Termékek",
    "PERSONALREQUIREDS":"Személyes szükségletek",
    "SYMULATIONS":"Szimulációk",
    "REQUIRED":"Szükséglet",
    "REGIST":"Regisztráció",

    "POLICY":"Adatkezelési tájékoztató",
    "TERMS":"Felhasználási feltételek",
    "PROTEST":"Visszaélés jelzése",
    "LICENCE":"Licensz",
    "SOURCE":"Forrás program",
    "COPYRIGHT":"Szabadon felhasználható",
    "SHARE":"Megosztás",
    "NICKNAME":"Bejelentkezési név",
    "NICKNAME_OR_EMAIL":"Bejelentkezési név vagy email",
    "USERNAME":"Bejelentkezési név",
    "REALNAME":"Valódi név",
    "EMAIL":"E-mail",
    "EMAIL_VERIFYED":"E-mail ellenörzött",
    "DISABLED":"Letiltott",
    "ENABLED":"Engedélyezett",
    "PASSWORD":"Jelszó",
    "PASSWORD_RETYPE":"Jelszó mégegyszer",
    "FBLOGIN": "Belépés Facebook -al",
    "GOOGLELOGIN": "Belépés Google -al",
    "DOREGIST":"Még nincs fiókod? - regisztrálj!",
	"REGISTHELP":"Valós email címet adjál meg! Aktiváló email-t kapsz erre a címre."+
        "A bejelentkezés csak az ebben szereplő linkre kattintás után lesz lehetséges. "+
        "A jelszó minimum 8 karakter, tartalmazzon kis és nagy betüt, számot, speciális karaktert! "+
        "Két lépcsős azonosítás bekapcsolása esetén az aktiváló email-ben kapod meg a konfiguráláshoz szükséges infokat, "+
        "szükség esetén az aktiváló levél újraküldsével újra lekérheted ezeket.",
	"REGISTHELP2":"Bejelentkezés után a \"profil\" oldalon avatar képet tölthetsz fel, jelszót változtathatsz, törölheted a fiókodat ",
    "PSW_REQUERED":"jelszót meg kell adni",
    "PSW_TO_SHORT":"a jelszó túl rövid (min 8 karakter szükséges)",
    "PSW_NOT_EQUALS":"a két jelszó nem azonos",
    "PSW_REQURED_NUMBERS":"a jelszó tartalmazzon számjegyet",
    "PSW_REQURED_LU_ALFABETS":"a jelszó tartalmazzon kis és nagy betüt",
    "PSW_REQURED_SPEC_CHARS":"a jelszó tartalmazzon speciális karaktert",
    "TWOFACTOR":"Google két lépcsős azonosítás",
    "SECRET_KEY":"Biztonsági kulcs",
    "NICK_OR_EMAIL_REQUIRED":"Belépési nevet vagy email -t meg kell adni",
    "EMAIL_SENDED":"Levél elküldve",
    "WRONG_DATA":"Hibás adatok, vagy a fiók még nincs aktiválva, vagy a fiól le van tiltva",
    "PASSWORD_REQUIRED":"Jalszót meg kell adni",
    "POLICYACCEPT":"Aza adatkezelési tájékoztatót elolvastam, megértettem, az adatkezelésbe bele egyezek.",

    "PROFILE":"Profil",
	"AVATARFILE":"Avatar képfájl (jpg vagy png, nem kötelező)",
	"NEWPASSWORD":"Az alábbi két mezőt csak akkor töltsd ki ha jelszót akarsz változtatni!",
    
    "USERNAME_REQUED":"Bejelentkezési nevet meg kell adni",
	"REALNAME_REQUED":"Valódi nevet meg kell adni",
	"EMAIL_REQUED":"E-mail -t meg kell adni",
	"PASSWORD_REQUED":"Jelszó nem lehet üres",
	"PASSWORDS_NOT_EQUALS":"A két beírt jelszó nem azonos",
    "USER_EXISTS":"Már van ilyen nevű fiók",
    "EMAIL_EXISTS":"Már van ezzel az e-mail -el fiók",
    "USER_NOT_FOUND":"Nincs ilyen fiók",
    "WRONG_PASSWORD":"Rossz jelszó",
    "USER_LOCKED_WAIT_5MINS":"Több mint 5 hibás belépési kisérlet miatt a bejelentkezés 5 percre letiltva.",
    "NOT_ACTIVATED":"A fiók nincs aktiválva",
    "RESEND_ACTIVATOR":"Aktiváló email újra küldése",
    "FORGET_PASSWORD":"Elfelejtett jelszó",
    "ONLY_IF_CAN_CHANGE_PSW":"Ha jelszót akarsz változtatni:",
    "ACCEPT1":"Az adatkezelési leírást",
    "ACCEPT2":"elolvastam, megértettem, hozzájárulok az adatkezeléshez",
    "ACCEPT_REQUED":"Adatkezeléshez hozzá kell járulni!",
    "MYDATA":"Adataim JSON formában",

    "GROUP":"Csoport",
    "GROUP_NAME_REQUED":"Csoport név nem lehet üres",
    "GROUP_EXISTS":"Már van ilyen csoport",
    "GROUP_BR_HELP":"További funkciókért kattints a névre",
    "ADMIN_CANNOT_UPDATE":"admin nem módosítható",
    "ADMIN_CANNOT_DELETE":"admin nem törölhető",

	
  /* demo */
  "DEMO":"demo",
  "DEMOS":"demos",
  "ID":"id",

  /* books */
  "BOOKS":"Könyvek",
  "BOOK":"Könyv",
  "TITLE":"Cím",
  "AUTHOR":"Szerző neve",
  "CATEGORY":"Kategória",
  "STORAGE":"Tároló hely",
  "BOOK_URL":"Könyv URL",
  "IMAGE_URL":"Birító kép URL",
  "YEAR":"Kiadás éve",
  "VOLUMES":"Kötetek száma",
  "CATEGORIES":"Kategóriák",
  "SUBSTRING":"(részlet)",

  /* account */
  "ACCOUNT":"fiók",
  "ACCOUNTS":"fiokok",
  "PASSWORD_REPEAT":"Jelszó ismét",
  "AVATAR":"avatar kép",
  "ERROR_COUNT":"Hiba számláló",
  "LOCKTIME":"Zárolás időpontja",

  "END":"Vége"
};
